default: &default
  host:     <%= ENV['DB_HOST'] %>
  adapter:  postgresql
  pool:     5
  timeout:  5000
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME_PROD'] %>