
---

version: '3'

services:
  sokoban-pg:
    build:
      context: .
      dockerfile: ./localenv/Dockerfile.pg
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    ports:
      - 9200:5432
    volumes:
      - volume-sokoban-pg:/var/lib/postgresql/data
  
  sokoban-lms:
    build:
      context: .
      dockerfile: ./localenv/Dockerfile.node
    volumes:
      - ./fronted:/application
    ports:
      - 9201:4200
    tty: true    

  sokoban-adminer:
    image: adminer
    restart: always
    ports:
      - 9202:8080

volumes:
  volume-sokoban-pg: