source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'dotenv-rails'
gem 'gon'
gem 'grape'
gem 'grape-entity'
gem 'grape-kaminari'
gem 'grape-swagger'
gem 'grape-swagger-rails'
gem 'devise'
gem 'kaminari'
gem 'rack-cors'

group :development, :test do
  gem 'selenium-webdriver'
  gem 'rmagick'
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
