name: 'Thinking Rabbit - "Original" collection (1988)'
slug: thinking-rabbit-original
description: |
  The 50 levels of Soko-Ban comes from the first two Japanese collections
  of Thinking Rabbit:  倉庫番 (Sokoban, December 1982) and 倉庫番2 (Sokoban 2,
  February 1984), more two levels of 倉庫番 (Sokoban, MSX, ASCII Corp., May 1984).