name: Alberto Borella
slug: alberto-borella
description: |
  Alberto's levels are refreshingly interesting, somewhat complex, and
  often quite challenging, with many unique design types are implemented.