# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7492222767c77d4dfdcf797ba68157fda773048d14e2248c9c72230085e4e1bb19b01da4e3957285f31c3ab8727fc68d912d417370e90a491f428dd751017d22

test:
  secret_key_base: 660bac5b1444f719675f1d74d1e512830197da69b0dd0126a97d1cb13d4ae9efb1fe3f4a6c991a8417db2ebc4da973cc4cc079550c6f7e698f29218ed204fb87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
