export const ACTION_GET_LEVEL_PACKS      = 'ACTION_GET_LEVEL_PACKS';
export const ACTION_GET_LEVEL_PACK       = 'ACTION_GET_LEVEL_PACK';
export const ACTION_GET_LEVEL            = 'ACTION_GET_LEVEL';
export const ACTION_GAME_INCREMENT_STEPS = 'ACTION_GAME_INCREMENT_STEPS';
